/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "border-default": "#E5E7EB",
          "success": "#10B981",
          "inverse-primary": "#bac3ff",
          "primary": "#2346d5",
          "on-primary-container": "#f4f2ff",
          "primary-fixed-dim": "#bac3ff",
          "on-secondary": "#ffffff",
          "pink-bg": "#FCE7F3",
          "border-light": "#F3F4F6",
          "on-tertiary-fixed-variant": "#793000",
          "surface-container": "#eeedf9",
          "on-secondary-fixed": "#410004",
          "on-tertiary": "#ffffff",
          "surface-container-low": "#f4f2fe",
          "on-tertiary-container": "#fff1eb",
          "success-bg": "#D1FAE5",
          "on-background": "#1a1b23",
          "tertiary-fixed": "#ffdbcb",
          "pink": "#EC4899",
          "surface-container-highest": "#e2e1ed",
          "background": "#fbf8ff",
          "tertiary-fixed-dim": "#ffb692",
          "secondary-fixed-dim": "#ffb3ad",
          "error": "#ba1a1a",
          "danger": "#EF4444",
          "accent-soft": "#EEF2FF",
          "on-primary-fixed": "#001159",
          "on-surface-variant": "#444655",
          "purple-bg": "#EDE9FE",
          "on-secondary-fixed-variant": "#930013",
          "surface-bright": "#fbf8ff",
          "surface-container-high": "#e8e7f3",
          "on-tertiary-fixed": "#341100",
          "on-primary-fixed-variant": "#0031c4",
          "purple": "#8B5CF6",
          "text-secondary": "#6B7280",
          "surface-tint": "#2e4edc",
          "text-muted": "#9CA3AF",
          "outline": "#747686",
          "surface-variant": "#e2e1ed",
          "on-error-container": "#93000a",
          "text-primary": "#1A1D23",
          "secondary": "#b61722",
          "outline-variant": "#c4c5d7",
          "tertiary": "#933c00",
          "on-error": "#ffffff",
          "surface-dim": "#dad9e5",
          "accent-hover": "#3451D1",
          "inverse-surface": "#2f3039",
          "on-primary": "#ffffff",
          "danger-bg": "#FEE2E2",
          "primary-container": "#4361ee",
          "secondary-fixed": "#ffdad7",
          "on-secondary-container": "#fffbff",
          "warning-bg": "#FEF3C7",
          "page-bg": "#F4F6FA",
          "warning": "#F59E0B",
          "primary-fixed": "#dee1ff",
          "surface": "#FFFFFF",
          "error-container": "#ffdad6",
          "surface-container-lowest": "#ffffff",
          "secondary-container": "#da3437",
          "tertiary-container": "#ba4e00",
          "on-surface": "#1a1b23",
          "inverse-on-surface": "#f1effc"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "topbar-height": "64px",
          "inline-gap": "10px",
          "card-padding": "20px",
          "stack-gap": "12px",
          "sidebar-width": "240px",
          "container-padding": "24px"
      },
      "fontFamily": {
          "body-lg": ["Poppins"],
          "display-lg": ["Poppins"],
          "label-sm": ["Poppins"],
          "label-md": ["Poppins"],
          "display-md": ["Poppins"],
          "body-md": ["Poppins"],
          "headline-sm": ["Poppins"]
      },
      "fontSize": {
          "body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
          "display-lg": ["30px", { "lineHeight": "1.2", "fontWeight": "700" }],
          "label-sm": ["11px", { "lineHeight": "1", "fontWeight": "600" }],
          "label-md": ["13px", { "lineHeight": "1", "fontWeight": "500" }],
          "display-md": ["28px", { "lineHeight": "1.2", "fontWeight": "700" }],
          "body-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
          "headline-sm": ["20px", { "lineHeight": "1.4", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
